"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# TODO: Change security settings before launching in production!

from pathlib import Path
import os
from dotenv import load_dotenv
from azure.identity import DefaultAzureCredential
import time

class AzureDbToken:
    def __init__(self):
        self.token = None
        self.expiry = 0
        self.cred = DefaultAzureCredential()

    def __str__(self):
        # If token is missing or expiring in less than 5 mins, refresh it
        if not self.token or self.expiry < (time.time() + 300):
            token_obj = self.cred.get_token("https://ossrdbms-aad.database.windows.net/.default")
            self.token = token_obj.token
            self.expiry = token_obj.expires_on
        return self.token

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Read DEBUG from environment so .env DEBUG=True is respected during development
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes')


# Parse comma-separated ALLOWED_HOSTS from environment
allowed_hosts_str = os.environ.get("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_str.split(",") if h.strip()]

# WEBSITE_SITE_NAME is automatically set by Azure App Service (system variable)
# It will NOT exist in local development, even if you have Azure credentials in .env
IS_IN_AZURE = 'WEBSITE_SITE_NAME' in os.environ

# Allow testing social-only auth locally by setting FORCE_SOCIALACCOUNT_ONLY=True in .env
# In production (Azure), this is always enforced regardless of env var
FORCE_SOCIALACCOUNT_ONLY = os.environ.get('FORCE_SOCIALACCOUNT_ONLY', 'False').lower() in ('1', 'true', 'yes')

# Break-glass control for username/password authentication.
# Default behavior:
# - Local dev: enabled (convenient for testing)
# - Azure prod: disabled (Microsoft SSO only)
# To temporarily enable emergency password login in Azure, set
# ALLOW_PASSWORD_ADMIN_LOGIN=True and restart the app.
ALLOW_PASSWORD_ADMIN_LOGIN = os.environ.get(
    'ALLOW_PASSWORD_ADMIN_LOGIN',
    'False' if IS_IN_AZURE else 'True'
).lower() in ('1', 'true', 'yes')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.microsoft',
    'axes',  # Brute force protection for admin login
    'core',
    'clinic_reports', # Clinic report form
]

# For local dev without Azure creds, add dummy provider
if not IS_IN_AZURE:
    INSTALLED_APPS.append('allauth.socialaccount.providers.dummy')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'axes.middleware.AxesMiddleware',  # Must be last for brute force protection
]

# django-axes configuration for brute force protection
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Brute force protection
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth social auth
]

# Only allow password auth when explicitly enabled (break-glass mode)
if ALLOW_PASSWORD_ADMIN_LOGIN:
    AUTHENTICATION_BACKENDS.insert(1, 'django.contrib.auth.backends.ModelBackend')

# Lock out after 5 failed login attempts
AXES_FAILURE_LIMIT = 5
# Lock out for 30 minutes
AXES_COOLOFF_TIME = 0.5  # Hours (0.5 = 30 minutes)
# Lockout key includes both username and IP to reduce bypass risk.
# Replaces deprecated AXES_ONLY_USER_FAILURES / AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP.
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

if IS_IN_AZURE:
    DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}
    try:
        DATABASES['default']['PASSWORD'] = AzureDbToken()
    except Exception as e:
        import logging
        logging.getLogger(__name__).critical(f"Failed to acquire Entra ID token in Azure environment. Error: {e}")

else:
    DATABASES['default']['PASSWORD'] = os.getenv("POSTGRES_PASSWORD")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    # Frontend TODO: Change this to whatever local port we are using for React
    # This allows the frontend to talk to the Django app without opening it up to
    # anyone on the internet
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # Defaults to requiring login
    ],

    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Use Django's standard session (cookie) mechanism (browser handles the cookie automatically)
        'rest_framework.authentication.SessionAuthentication',
    ],

    # Pagination to avoid server crashes when loading a large dataset
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,

    # Global API rate limiting to reduce abuse / DoS risk (CWE-770)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Override via env in deployment as needed
        'anon': os.environ.get('DRF_THROTTLE_ANON', '60/minute'),
        'user': os.environ.get('DRF_THROTTLE_USER', '120/minute'),
    },
}

# This allows us to use Microsoft Entra for login
# All secrets should ALWAYS stay in local environment variables!
SOCIALACCOUNT_PROVIDERS = {
    'microsoft': {
        'APP': {
            'client_id': os.environ.get('MICROSOFT_LOGIN_CLIENT_ID'), # Same as azure client id but that name is reserved in Azure
            'secret': os.environ.get('AZURE_SECRET'),
        },
        'TENANT': os.environ.get('AZURE_TENANT_ID'), # TODO: Replace with UA's tenant in production
        'SCOPE': ['User.Read'],
        'AUTH_PARAMS': {'prompt': 'select_account'},
    }
}

# For local dev without Azure creds, add dummy provider config
if not IS_IN_AZURE:
    SOCIALACCOUNT_PROVIDERS['dummy'] = {}


# Helper function to determine LOGIN_URL based on Azure credentials
def get_login_url():
    """Determine the login URL based on whether Azure credentials are configured."""
    if IS_IN_AZURE:
        return '/accounts/microsoft/login/'
    else:
        return '/accounts/login/'  # Show provider chooser in local environment


# When Azure credentials are present, skip allauth chooser and go straight to Microsoft
# Otherwise, show the provider chooser to allow dummy login
LOGIN_URL = get_login_url()
    
LOGIN_REDIRECT_URL = '/' # Redirect to homepage after login
LOGOUT_REDIRECT_URL = '/' # Redirect to homepage after logout

# Identify the site
SITE_ID = 1

# Use custom social account adapter to restrict to UA email domains
SOCIALACCOUNT_ADAPTER = 'core.adapters.CustomSocialAccountAdapter'

# Force social auth only in production (Azure), but allow local accounts for testing
# This prevents bypassing Microsoft SSO via local Django accounts in production
# Required setting for SOCIALACCOUNT_ONLY
ACCOUNT_EMAIL_VERIFICATION = 'none'

# Enforce social-only auth in Azure production, or locally if FORCE_SOCIALACCOUNT_ONLY=True
# This allows testing the production behavior locally without Azure managed identity
SOCIALACCOUNT_ONLY = IS_IN_AZURE or FORCE_SOCIALACCOUNT_ONLY

# When hitting a provider login URL (e.g. /accounts/microsoft/login/),
# immediately start the OAuth flow instead of showing an extra
# "You are about to log in with ..." confirmation page.
SOCIALACCOUNT_LOGIN_ON_GET = True

# CSRF and cookie security settings
# Allow browsers to send cookies with cross-origin XHR when configured
CORS_ALLOW_CREDENTIALS = True

# Trusted origins (comma-separated) can be set via env for deployed domains
# Example: CSRF_TRUSTED_ORIGINS='https://example.com,https://sub.example.com'
CSRF_TRUSTED_ORIGINS = [x for x in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if x]

# For Azure: recognize X-Forwarded-Proto header from reverse proxy to correctly detect HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Use secure cookies in Azure by default.
# Local Docker/dev commonly runs over HTTP, so forcing Secure cookies there breaks
# session-based auth flows (e.g., allauth dummy/microsoft state handling).
SECURE_COOKIES = os.environ.get('SECURE_COOKIES', 'True' if IS_IN_AZURE else 'False').lower() in ('1', 'true', 'yes')
CSRF_COOKIE_SECURE = SECURE_COOKIES
SESSION_COOKIE_SECURE = SECURE_COOKIES

# Sane defaults for SameSite to reduce CSRF exposure while allowing normal
# navigation-based logins (use 'Strict' if you only need same-site access)
CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Lax')

# Extra security headers (recommended for FERPA-sensitive apps)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# HSTS: Enforce HTTPS for all future requests
# Start with 1 hour (3600s), increase to 1 year (31536000s) after testing in production
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '3600' if IS_IN_AZURE else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Enforce HTTPS redirect (Azure reverse proxy sets X-Forwarded-Proto correctly)
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True' if IS_IN_AZURE else 'False').lower() in ('1', 'true', 'yes')

# Referrer Policy: Don't leak user activity to external sites
SECURE_REFERRER_POLICY = "same-origin"