# Generated by Django 5.2.10 on 2026-01-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('clinical_site', models.CharField(max_length=200)),
                ('sport', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Soccer', 'Soccer'), ('Hockey', 'Hockey'), ('Baseball', 'Baseball'), ('Volleyball', 'Volleyball'), ('Tennis', 'Tennis'), ('Track and Field', 'Track and Field'), ('Swimming', 'Swimming'), ('Lacrosse', 'Lacrosse')], max_length=50)),
                ('immediate_emergency_care', models.IntegerField()),
                ('musculoskeletal_exam', models.IntegerField()),
                ('non_musculoskeletal_exam', models.IntegerField()),
                ('taping_bracing', models.IntegerField()),
                ('rehabilitation_reconditioning', models.IntegerField()),
                ('modalities', models.IntegerField()),
                ('pharmacology', models.IntegerField()),
                ('injury_illness_prevention', models.IntegerField()),
                ('non_sport_patient', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
