# Generated by Django 5.2.11 on 2026-02-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicreport',
            name='interacted_hcps',
            field=models.BooleanField(default=False),
        ),
    ]
