# Generated by Django 5.2.11 on 2026-02-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_reports', '0002_clinicreport_interacted_hcps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicreport',
            name='interacted_hcps',
            field=models.BooleanField(default=False, verbose_name='Interacted with other Health Care Professionals this week?'),
        ),
    ]
