# Generated by Django 5.2.11 on 2026-02-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_reports', '0003_alter_clinicreport_interacted_hcps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicreport',
            name='clinical_site',
        ),
    ]
