# Generated by Django 5.2.11 on 2026-02-13 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_reports', '0004_remove_clinicreport_clinical_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clinicreport',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic_reports.sport'),
        ),
    ]
