# Generated by Django 5.2.11 on 2026-02-12 22:26

from django.db import migrations

def add_initial_sports(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Sport = apps.get_model('clinic_reports', 'Sport')
    initial_sports = ['Football',
                      'Basketball',
                      'Soccer',
                      'Hockey',
                      'Baseball',
                      'Volleyball',
                      'Tennis',
                      'Track and Field',
                      'Swimming',
                      'Lacrosse'
                     ]


    for sport_name in initial_sports:
        # get_or_create prevents duplicates if you run this twice!
        Sport.objects.get_or_create(name=sport_name)

class Migration(migrations.Migration):

    dependencies = [
        ('clinic_reports', '0005_sport'),
    ]

    operations = [
    ]
