# Generated by Django 5.2.11 on 2026-02-13 17:02

from django.db import migrations

def add_initial_sports(apps, schema_editor):

    Sport = apps.get_model('clinic_reports', 'Sport')
    initial_sports = ['Football',
                      'Basketball',
                      'Soccer',
                      'Hockey',
                      'Baseball',
                      'Volleyball',
                      'Tennis',
                      'Track and Field',
                      'Swimming',
                      'Lacrosse'
                     ]

    for sport_name in initial_sports:
        # get_or_create prevents duplicates if you run this twice!
        Sport.objects.get_or_create(name=sport_name)

class Migration(migrations.Migration):

    dependencies = [
        ('clinic_reports', '0005_sport_alter_clinicreport_sport'),
    ]

    operations = [
        migrations.RunPython(add_initial_sports)
    ]
