# Generated by Django 5.2.11 on 2026-02-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_reports', '0006_insert_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicreport',
            name='sport_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic_reports.sport'),
        ),
    ]
