# Generated by Django 5.2.11 on 2026-02-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_reports', '0006_add_initial_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicreport',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall')], default='Spring', max_length=10),
        ),
        migrations.AddField(
            model_name='clinicreport',
            name='week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
