# Generated by Django 5.2.11 on 2026-02-12 22:32

from django.db import migrations


def migrate_sport_to_fk(apps, schema_editor):
    ClinicReport = apps.get_model('clinic_reports', 'ClinicReport')
    Sport = apps.get_model('clinic_reports', 'Sport')
    
    for report in ClinicReport.objects.all():
        if report.sport:  # If the old CharField has a value
            try:
                sport_obj = Sport.objects.get(name=report.sport)
                report.sport_fk = sport_obj
                report.save()
            except Sport.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_reports', '0007_clinicreport_sport_fk'),
    ]

    operations = [
        migrations.RunPython(migrate_sport_to_fk),
    ]
