# Generated by Django 5.2.11 on 2026-02-12 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_reports', '0008_auto_20260212_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicreport',
            name='sport',
        ),
        migrations.RenameField(
            model_name='clinicreport',
            old_name='sport_fk',
            new_name='sport',
        ),
    ]
