# Generated by Django 5.2.11 on 2026-02-12 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_reports', '0009_remove_clinicreport_sport_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicreport',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic_reports.sport'),
        ),
    ]
