# Generated by Django 5.2.11 on 2026-02-12 23:05

from django.db import migrations

def add_initial_sports(apps, schema_editor):

    Sport = apps.get_model('clinic_reports', 'Sport')
    initial_sports = ['Football',
                      'Basketball',
                      'Soccer',
                      'Hockey',
                      'Baseball',
                      'Volleyball',
                      'Tennis',
                      'Track and Field',
                      'Swimming',
                      'Lacrosse'
                     ]


    for sport_name in initial_sports:
        # get_or_create prevents duplicates if you run this twice!
        Sport.objects.get_or_create(name=sport_name)


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_reports', '0010_make_sport_non_nullable'),
    ]

    operations = [migrations.RunPython(add_initial_sports)]
