# Generated by Django 5.2.13 on 2026-04-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_logging', '0002_alter_adminportallog_event_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminportallog',
            new_name='user_loggin_event_t_5f17c7_idx',
            old_name='user_loggin_event_t_6f693d_idx',
        ),
        migrations.RenameIndex(
            model_name='adminportallog',
            new_name='user_loggin_created_96c40a_idx',
            old_name='user_loggin_created_6e4a12_idx',
        ),
    ]
